CycloneDX/cyclonedx-go

- .github/workflows/ci.yml
not removing support for go 1.14 for now
Signed-off-by: nscuro <nscuro@protonmail.com>
> ci: build against go 1.17

- .github/workflows/ci.yml
- .licenserc.yml
- example_test.go
also remove sbom generation from ci workflow, it doesn't serve any purpose
Signed-off-by: nscuro <nscuro@protonmail.com>
> build(ci): add license header check

- cyclonedx.go
fixes #25
BREAKING CHANGE: the type of `VulnerabilityRating.Score` changed from `float64` to `*float64`.
Signed-off-by: nscuro <nscuro@protonmail.com>
> fix: make vuln rating score optional

- cyclonedx.go
@nscuro, I was reading through the codebase and saw a couple of `EMail` (rather than `email`) instances. Was this intentional? If not, here's a PR. If it is, apologies for the noise and you can close this PR.
> Edit casing of email

- cyclonedx.go
- encode_test.go
Property and other items were encoded as `innerxml` instead of
`chardata`. Innerxml does not encode special XML chars.
See also: https://github.com/golang/go/issues/16604
Fixes #31
> fix: encoding of XML chars in tags

- cyclonedx.go
- link.go
- link_example_test.go
- link_test.go
Signed-off-by: nscuro <nscuro@protonmail.com>
> feat: add support for bom links

- cyclonedx.go
- cyclonedx_test.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-vulnerability.json
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-vulnerability.xml
- testdata/valid-vulnerability.json
- testdata/valid-vulnerability.xml
Closes https://github.com/CycloneDX/cyclonedx-go/issues/38
> fix: add missing Properties

- encode.go
- encode_test.go
This PR adds a way to specify HTML escaping for JSON format. The default is to _escape_ certain characters, but some users do not want this behavior and would rather only escape the necessary double quote with `\"` when outputting JSON.
> feat: option to specify HTML escaping for JSON format

- convert.go
- cyclonedx.go
- cyclonedx_json.go
- encode_test.go
- testdata/snapshots/cyclonedx-go-TestJsonBOMEncoder_EncodeVersion-func3-1.2.bom.json
- testdata/snapshots/cyclonedx-go-TestJsonBOMEncoder_EncodeVersion-func3-1.3.bom.json
- testdata/snapshots/cyclonedx-go-TestJsonBOMEncoder_EncodeVersion-func3-1.4.bom.json
This adds a `$schema` field to the JSON output, to achieve parity with the CycloneDX JavaScript library. The value points to the JSON schema definition file at cyclonedx.org.
> feat: add JSON Schema to JSON output

- cyclonedx.go
- cyclonedx_json.go
- cyclonedx_string.go
- cyclonedx_xml.go
- encode_test.go
- example_test.go
- schema/bom-1.5.schema.json
- schema/bom-1.5.xsd
- testdata/snapshots/cyclonedx-go-TestJsonBOMEncoder_EncodeVersion-func3-1.5.bom.json
- testdata/snapshots/cyclonedx-go-TestXmlBOMEncoder_EncodeVersion-func1-1.5.bom.xml
- validate_json_test.go
- validate_xml_test.go
This adds the new schemas, `SpecVersion` variables, and updates existing tests to use v1.5. The default `specVersion` set by `NewBOM` is now `SpecVersion1_5`.
> **Note**  
> Decoupled from #90 in favor of smaller PRs.
> feat(spec1-5): add initial support for spec v1.5

- convert.go
- cyclonedx.go
This PR adds new component types that have been introduced in spec v1.5.
> feat(spec1-5): add new component types

- cyclonedx_json.go
- cyclonedx_xml.go
unmarshal bom on v1.5 return invalid specification version
Close: #101
> fix: unmarshal bom on v1.5 return invalid specification version

- .github/workflows/ci.yml
- .golangci.yml
- cyclonedx_xml.go
- validate_json_test.go
- validate_xml_test.go
Enables errorlint and gci.
It replaces gofmt by gofumpt as it is an extension. 
Disable setup-go cache to benefit from the golangci-lint-action’s cache.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> ci: enable more linters

- schema/bom-1.6.schema.json
- schema/bom-1.6.xsd
Adding schema definitions from https://github.com/CycloneDX/specification/tree/1.6/schema.
Closes #152.
> feat(1.6): add schema definitions for CycloneDX 1.6

- convert.go
- convert_test.go
- cyclonedx.go
This extends type `EvidenceOccurrence` with additional fields from the 1.6 spec. Logic has been added to the conversion to make sure they don't show up in lower spec versions.
Closes #156.
> feat(1.6): extend EvidenceOccurrence

- cyclonedx_json.go
- cyclonedx_xml.go
For specification 1.6, this adds...
* `$schema` in JSON output
* `xmlns` in XML output
> feat(1.6): add JSON schema, XML namespace

- convert.go
- cyclonedx.go
This adds a new property `BOM.Definitions` for further 1.6 spec support.
Closes #158.
> feat(1.6): add BOM.Definitions

- cyclonedx.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-definitions.json
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-definitions.xml
- testdata/valid-definitions.json
- testdata/valid-definitions.xml
This adds roundtrip tests for `BOM.Definitions` (added in #161) and fixes some mistakes on JSON, XML labels along the way.
> fix(1.6): fix json, xml labels on BOM.Definitions

- convert.go
- convert_test.go
- cyclonedx.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-license-licensing.json
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-license-name.json
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-license-licensing.xml
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-license-name.xml
- testdata/valid-license-licensing.json
- testdata/valid-license-licensing.xml
- testdata/valid-license-name.json
- testdata/valid-license-name.xml
This adds `License.Acknowledgement` for spec 1.6 support.
Closes #166.
> feat(1.6): add License.Acknowledgement

- convert.go
- cyclonedx.go
This adds `.Declarations` to the `BOM` struct.
Closes #157.
> feat(1.6): add BOM.Declarations

- cyclonedx.go
This adds new type `PostalAddress` from the 1.6 spec.
Closes #172.
Since this is a part of `OrganizationEntity`, which is being referenced in many locations, I will create a new issue and PR for conversion to legacy spec versions. Otherwise this might become too much.
> feat(1.6): add PostalAddress type

- convert.go
- convert_test.go
This adds `func convertOrganizationalEntity()` and targets occurences of `OrganizationalEntity` during spec conversion. This is an addendum to #173.
Closes #174.
> fix(1.6): convert occurrences of OrganizationalEntity

- convert.go
- cyclonedx.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-metadata-author.json
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-metadata-manufacture.json
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-metadata-author.xml
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-metadata-manufacture.xml
- testdata/valid-metadata-author.json
- testdata/valid-metadata-author.xml
- testdata/valid-metadata-manufacture.json
- testdata/valid-metadata-manufacture.xml
Adds `BOMRef` to `OrganizationalEntity` [[1.5 spec](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.5.schema.json#L363-L367)] & `OrganizationalContact` [[1.5 spec](https://github.com/CycloneDX/specification/blob/master/schema/bom-1.5.schema.json#L363-L367)] which were added in the CycloneDX 1.5 spec.
I've kept this in the `1.6` spec branch as additional conversation functions were added to handle `OrganizationalEntity`s and reduce merge conflicts.
Fixes issue: https://github.com/CycloneDX/cyclonedx-go/issues/180
> Adds missing BOMRef on OrganizationalEntity & OrganizationalContact

- convert.go
- convert_test.go
- cyclonedx.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-component-authors.json
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-component-manufacturer.json
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-metadata-manufacturer.json
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-component-authors.xml
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-component-manufacturer.xml
- testdata/snapshots/cyclonedx-go-TestRoundTripXML-func1-valid-metadata-manufacturer.xml
- testdata/valid-component-authors.json
- testdata/valid-component-authors.xml
- testdata/valid-component-manufacturer.json
- testdata/valid-component-manufacturer.xml
- testdata/valid-metadata-manufacturer.json
- testdata/valid-metadata-manufacturer.xml
- adds `manufacturer` field to `Metadata` and `Component`
- adds `authors` field to `Component`
- adds roundtrip testdata for above
> feat: add manufacturer and authors

- convert_test.go
Adds missing license header to new `convert_test.go` file.
> chore: add license header

- convert.go
- convert_test.go
- cyclonedx.go
- cyclonedx_json.go
- cyclonedx_json_test.go
- cyclonedx_xml.go
- cyclonedx_xml_test.go
- testdata/snapshots/cyclonedx-go-TestRoundTripJSON-func1-valid-evidence.json
- testdata/valid-evidence.json
in CycloneDX 1.6 type of `Component.Evidence.Identity` has been changed to `[]Identity`.
`Identity` as `struct` was marked as `deprecated`.
https://cyclonedx.org/docs/1.6/json/#tab-pane_metadata_component_evidence_identity_oneOf_i0
- Close #192
> fix: change `Component.Evidence.Identity` to array

- cyclonedx.go
add the missing `Tags` and `Signature` properties on the appropriate structs, bringing parity with the [JSON schema](https://github.com/CycloneDX/cyclonedx-go/blob/master/schema/bom-1.6.schema.json)
> fix: add missing `Tags` and `Signature` properties
